package websocket

import (
	"bytes"
	"encoding/json"
	"log"
	"questhub/models/database"
	"questhub/service"
	"time"

	"github.com/gorilla/websocket"
)

const (
	// Time allowed to write a message to the peer.
	writeWait = 10 * time.Second

	// Time allowed to read the next pong message from the peer.
	pongWait = 60 * time.Second

	// Send pings to peer with this period. Must be less than pongWait.
	pingPeriod = (pongWait * 9) / 10

	// Maximum message size allowed from peer.
	maxMessageSize = 512
)

var (
	newline = []byte{'\n'}
	space   = []byte{' '}
)

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
}

// Client is a middleman between the websocket connection and the hub.
type Client struct {
	hub *Hub

	// The websocket connection.
	conn *websocket.Conn

	// Buffered channel of outbound messages.
	send chan []byte

	// UserID of the connected user
	UserID string
}

// readPump pumps messages from the websocket connection to the hub.
//
// The application runs readPump in a per-connection goroutine. The application
// ensures that there is at most one reader on a connection by executing all
// reads from this goroutine.
func (c *Client) readPump() {
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
	}()
	c.conn.SetReadLimit(maxMessageSize)
	c.conn.SetReadDeadline(time.Now().Add(pongWait))
	c.conn.SetPongHandler(func(string) error { c.conn.SetReadDeadline(time.Now().Add(pongWait)); return nil })
	for {
		_, message, err := c.conn.ReadMessage()
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				log.Printf("error: %v", err)
			}
			break
		}
		message = bytes.TrimSpace(bytes.Replace(message, newline, space, -1))

		// Parse message
		var msgMap map[string]interface{}
		if err := json.Unmarshal(message, &msgMap); err != nil {
			log.Printf("error unmarshalling message: %v", err)
			continue
		}

		// Handle Chat Messages
		if msgType, ok := msgMap["type"].(string); ok && (msgType == "CHAT_GLOBAL" || msgType == "CHAT_PRIVATE" || msgType == "EVENT") {
			// Enrich message with server-side data
			msgMap["sender_id"] = c.UserID
			msgMap["created_at"] = time.Now()
			// SenderName should ideally be fetched from DB or context, for now assuming it's sent or we fetch it
			// For simplicity, let's assume the frontend sends the sender_name for now, or we fetch it.
			// Ideally, we should fetch the user to get the name to prevent spoofing.
			// TODO: Fetch user name from service.GetUser(c.UserID)

			// Construct ChatMessage for DB
			chatMsg := database.ChatMessage{
				ID:         "",                         // Generated by DB
				GameID:     msgMap["game_id"].(string), // Frontend must send game_id
				SenderID:   c.UserID,
				SenderName: msgMap["sender_name"].(string), // Should be validated
				Content:    msgMap["content"].(string),
				Type:       msgType,
				CreatedAt:  time.Now(),
			}

			if targetID, ok := msgMap["target_id"].(string); ok {
				chatMsg.TargetID = &targetID
			}

			// Save to DB
			if err := service.SaveMessage(chatMsg); err != nil {
				log.Printf("error saving message: %v", err)
				continue // Do not broadcast if save fails
			}

			// Re-marshal to send with ID and timestamp if needed, or just forward the map
			// Better to send the saved struct to ensure consistency
			// However, we need the ID generated by DB if we want to send it back.
			// For now, let's trust the broadcast.

			// We need to re-marshal the map to include the updates (like timestamp)
			updatedMessage, _ := json.Marshal(msgMap)
			c.hub.broadcast <- updatedMessage
		} else {
			// Unknown message type or not a chat message, just broadcast (e.g. character update is handled elsewhere)
			c.hub.broadcast <- message
		}
	}
}

// writePump pumps messages from the hub to the websocket connection.
//
// A goroutine running writePump is started for each connection. The
// application ensures that there is at most one writer to a connection by
// executing all writes from this goroutine.
func (c *Client) writePump() {
	ticker := time.NewTicker(pingPeriod)
	defer func() {
		ticker.Stop()
		c.conn.Close()
	}()
	for {
		select {
		case message, ok := <-c.send:
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if !ok {
				// The hub closed the channel.
				c.conn.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}

			w, err := c.conn.NextWriter(websocket.TextMessage)
			if err != nil {
				return
			}
			w.Write(message)

			// Add queued chat messages to the current websocket message.
			n := len(c.send)
			for i := 0; i < n; i++ {
				w.Write(newline)
				w.Write(<-c.send)
			}

			if err := w.Close(); err != nil {
				return
			}
		case <-ticker.C:
			c.conn.SetWriteDeadline(time.Now().Add(writeWait))
			if err := c.conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				return
			}
		}
	}
}
